import { useState } from 'react'
import { useCommuteStore } from '@/stores/commuteStore'
import { CommuteRoutine, CommuteStep } from '@/types'
import { Button } from '@/components/ui/button'
import { RoutineForm, RoutineCard, TimeCalculator } from '@/components/commute'
import { Plus, Train } from 'lucide-react'
import { useToast } from '@/hooks/useToast'

export default function Commute() {
  const { routines, selectedRoutine, addRoutine, updateRoutine, deleteRoutine, selectRoutine } =
    useCommuteStore()
  const [isFormOpen, setIsFormOpen] = useState(false)
  const [editingRoutine, setEditingRoutine] = useState<CommuteRoutine | null>(null)
  const { toast } = useToast()

  const handleAddRoutine = (data: {
    name: string
    destination?: string
    defaultArrivalTime?: string
    steps: CommuteStep[]
  }) => {
    const newRoutine: CommuteRoutine = {
      id: '', // will be generated by store
      name: data.name,
      destination: data.destination || '',
      steps: data.steps,
      totalMinutes: data.steps.reduce((sum, s) => sum + s.durationMinutes, 0),
      defaultArrivalTime: data.defaultArrivalTime,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    }
    addRoutine(newRoutine)
    toast({ title: '루틴이 추가되었습니다' })
  }

  const handleEditRoutine = (data: {
    name: string
    destination?: string
    defaultArrivalTime?: string
    steps: CommuteStep[]
  }) => {
    if (!editingRoutine) return
    updateRoutine(editingRoutine.id, {
      name: data.name,
      destination: data.destination,
      defaultArrivalTime: data.defaultArrivalTime,
      steps: data.steps,
      totalMinutes: data.steps.reduce((sum, s) => sum + s.durationMinutes, 0),
    })
    setEditingRoutine(null)
    toast({ title: '루틴이 수정되었습니다' })
  }

  const handleDeleteRoutine = (routineId: string) => {
    deleteRoutine(routineId)
    if (selectedRoutine?.id === routineId) {
      selectRoutine(null)
    }
    toast({ title: '루틴이 삭제되었습니다' })
  }

  return (
    <div className="space-y-6">
      {/* 헤더 */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-3">
          <Train className="h-6 w-6 text-blue-600" />
          <div>
            <h1 className="text-xl font-bold">출퇴근 시간 계산기</h1>
            <p className="text-sm text-gray-500">
              루틴을 저장하고 도착 시간에 맞춰 출발 시간을 계산하세요
            </p>
          </div>
        </div>
        <Button onClick={() => setIsFormOpen(true)}>
          <Plus className="h-4 w-4 mr-2" />
          새 루틴
        </Button>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* 루틴 목록 */}
        <div className="space-y-4">
          <h2 className="font-semibold text-gray-700">저장된 루틴</h2>
          {routines.length === 0 ? (
            <div className="text-center py-12 border border-dashed rounded-lg">
              <Train className="h-12 w-12 text-gray-300 mx-auto mb-4" />
              <p className="text-gray-500 mb-4">저장된 루틴이 없습니다</p>
              <Button variant="outline" onClick={() => setIsFormOpen(true)}>
                <Plus className="h-4 w-4 mr-2" />
                첫 루틴 추가하기
              </Button>
            </div>
          ) : (
            <div className="space-y-3">
              {routines.map((routine) => (
                <RoutineCard
                  key={routine.id}
                  routine={routine}
                  isSelected={selectedRoutine?.id === routine.id}
                  onSelect={() => selectRoutine(routine)}
                  onEdit={() => {
                    setEditingRoutine(routine)
                  }}
                  onDelete={() => handleDeleteRoutine(routine.id)}
                />
              ))}
            </div>
          )}
        </div>

        {/* 시간 계산기 */}
        <div className="space-y-4">
          <h2 className="font-semibold text-gray-700">시간 계산</h2>
          {selectedRoutine ? (
            <TimeCalculator routine={selectedRoutine} />
          ) : (
            <div className="text-center py-12 border border-dashed rounded-lg">
              <p className="text-gray-500">
                루틴을 선택하면 시간을 계산할 수 있습니다
              </p>
            </div>
          )}
        </div>
      </div>

      {/* 추가 폼 */}
      <RoutineForm
        open={isFormOpen}
        onClose={() => setIsFormOpen(false)}
        onSubmit={handleAddRoutine}
      />

      {/* 수정 폼 */}
      <RoutineForm
        open={!!editingRoutine}
        onClose={() => setEditingRoutine(null)}
        onSubmit={handleEditRoutine}
        routine={editingRoutine || undefined}
        isEdit
      />
    </div>
  )
}
